linters-settings:
  goimports:
    local-prefixes: github.com/OpenLabsHQ/CLI

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports

run:
  timeout: 5m