name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64

  verify-lint-passing:
    name: Verify Lint Passing
    needs: golangci
    runs-on: ubuntu-latest
    steps:
      - name: Lint check passed
        run: echo "All lint checks passed!"
